# Generated by Django 5.2.17 on 2026-09-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "主题", "verbose_name_plural": "主题"},
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_text", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning_logs.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "条目",
                "verbose_name_plural": "条目",
            },
        ),
    ]
