# Generated by Django 5.2.17 on 2026-09-27 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0002_alter_topic_options_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="learning_logs.topic",
            ),
        ),
    ]
